# Generated by Django 3.1.6 on 2021-02-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kategorimodel',
            table='kategori',
        ),
    ]
