# Generated by Django 3.1.6 on 2021-02-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210218_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorimodel',
            options={'verbose_name_plural': 'Kategoriler'},
        ),
    ]
