# Generated by Django 3.1.6 on 2021-02-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_yazilarmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='yazilarmodel',
            table='yazi',
        ),
    ]
