# Generated by Django 3.1.6 on 2021-02-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210221_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazilarmodel',
            name='resim',
            field=models.ImageField(blank=True, upload_to='yazi_resimleri'),
        ),
    ]
